{{- if and (.Values.spegel.routerRedis.enabled) (.Values.spegel.routerRedis.secretAutoCreate) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.spegel.routerRedis.secretName }}
  namespace: {{ include "spegel.namespace" . }}
type: Opaque
data:
  address: {{ .Values.spegel.routerRedis.address | b64enc | quote }}
  username: {{ .Values.spegel.routerRedis.username | b64enc | quote }}
  password: {{ .Values.spegel.routerRedis.password | b64enc | quote }}
  sentinelUsername: {{ .Values.spegel.routerRedis.sentinel.username | b64enc | quote }}
  sentinelPassword: {{ .Values.spegel.routerRedis.sentinel.password | b64enc | quote }}
{{ end }}
