{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "valkey.fullname" . }}
  namespace: {{ include "valkey.namespace" . }}
  labels:
    {{- include "valkey.labels" . | nindent 4 }}
type: Opaque
stringData:
  address: '{{ include "valkey.fullname" . }}.{{ include "valkey.namespace" . }}.svc.{{ .Values.clusterDomain }}:{{ .Values.service.port }}'
  {{- if .Values.auth.username }}
  username: {{ .Values.auth.username | quote }}
  {{- end }}
  {{ .Values.auth.existingSecretPasswordKey }}: {{ .Values.auth.password | quote }}
{{- end }}
